project_id = "nhzspvllzlubturohass"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "https://nhzspvllzlubturohass.supabase.co/**",
  "https://07dc8c76-e23d-4b0c-a41a-3f16d01f0993.lovableproject.com",
  "https://07dc8c76-e23d-4b0c-a41a-3f16d01f0993.lovableproject.com/",
  "https://07dc8c76-e23d-4b0c-a41a-3f16d01f0993.lovableproject.com/auth/callback",
  "https://07dc8c76-e23d-4b0c-a41a-3f16d01f0993.lovableproject.com/payment-auth",
  "https://07dc8c76-e23d-4b0c-a41a-3f16d01f0993.lovableproject.com/payment-auth?plan=monthly",
  "https://07dc8c76-e23d-4b0c-a41a-3f16d01f0993.lovableproject.com/payment-auth?plan=yearly",
  "http://localhost:3000",
  "http://localhost:3000/",
  "http://localhost:3000/auth/callback",
  "http://localhost:3000/payment-auth",
  "http://localhost:3000/payment-auth?plan=monthly",
  "http://localhost:3000/payment-auth?plan=yearly"
]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[db]
port = 54322

[edge_functions]
enabled = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.send-custom-auth-email]
verify_jwt = false

[functions.translate-content]
verify_jwt = true

[studio]
enabled = true
port = 54323