// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhzspvllzlubturohass.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5oenNwdmxsemx1YnR1cm9oYXNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3Mjc0MjUsImV4cCI6MjA2OTMwMzQyNX0.QH0-ucx3pAXwlecQdsudgmJMbrjI8FvjEhFG8I3vOhA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});